#!/usr/bin/env bash
set -e

if [[ 'gh-pages' == $TRAVIS_BRANCH ]] ; then
  cd _site
  git init

  git config user.name "Travis CI"
  git config user.email "balint.kiss.501@gmail.com"

  git add .
  git commit -m "Deploy"

  git push --force --quiet "https://${git_user}:${git_password}@${git_target}" master:master > /dev/null 2>&1
else
  echo 'Invalid branch. You can only deploy from gh-pages.'
  exit 1
fi
